/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BJK.form;

import javax.swing.table.DefaultTableModel;
import BJK.controler.ControllerReport;
import java.math.MathContext;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Salman Alfarissy
 */
public class FormReport1 extends javax.swing.JFrame {
    private FormLogin login;
    private FormMenu menu;
    private FormHome home;
    private ControllerReport control;
    
    private String id_kasir;
    private String namakasir;
    
    

    /**
     * Creates new form FormReport1
     */
    
    public FormReport1() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("src/gambar/logo32.png");
        setIconImage(icon.getImage());
        control = new ControllerReport(this); 
        control.tampil_Reportnow();
         this.setLocationRelativeTo(null);
    }

    public JTable getTblreport() {
        return tblreport;
    }

    public JTextField getTxttot() {
        return txttot;
    }

    public String getId_kasir() {
        return id_kasir;
    }

    public void setId_kasir(String id_kasir) {
        this.id_kasir = id_kasir;
    }

    public String getNamakasir() {
        return namakasir;
    }

    public void setNamakasir(String namakasir) {
        this.namakasir = namakasir;
    }

    public JComboBox<String> getC_bln() {
        return c_bln;
    }

    public JComboBox<String> getC_tgl() {
        return c_tgl;
    }

    public JComboBox<String> getC_thn() {
        return c_thn;
    }

    public JButton getBtnfind() {
        return btnfind;
    }

    public JButton getBtnfindall() {
        return btnfindall;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblreport = new javax.swing.JTable();
        btnlogout = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btnmenu1 = new javax.swing.JButton();
        txttot = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        c_tgl = new javax.swing.JComboBox<>();
        c_bln = new javax.swing.JComboBox<>();
        c_thn = new javax.swing.JComboBox<>();
        btnfindall = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        btnfindanow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Trans", "Nama Menu", "Nama Kasir", "Tanggal Trans", "Jumlah Terjual", "Keuntungan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblreport);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 260, 700, 290);

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Iconlogout2.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout);
        btnlogout.setBounds(730, 0, 150, 40);

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/print.png"))); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint);
        btnprint.setBounds(80, 560, 60, 60);

        btnhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Iconhome.png"))); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome);
        btnhome.setBounds(0, 0, 60, 60);

        btnmenu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconMenu.png"))); // NOI18N
        btnmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu1);
        btnmenu1.setBounds(70, 0, 120, 60);

        txttot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotActionPerformed(evt);
            }
        });
        getContentPane().add(txttot);
        txttot.setBounds(590, 560, 160, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 560, 40, 30);

        c_tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        c_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_tglActionPerformed(evt);
            }
        });
        getContentPane().add(c_tgl);
        c_tgl.setBounds(60, 200, 80, 30);

        c_bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(c_bln);
        c_bln.setBounds(160, 200, 80, 30);

        c_thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2000" }));
        getContentPane().add(c_thn);
        c_thn.setBounds(250, 200, 80, 30);

        btnfindall.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfindall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconfindall.png"))); // NOI18N
        btnfindall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindallActionPerformed(evt);
            }
        });
        getContentPane().add(btnfindall);
        btnfindall.setBounds(150, 560, 60, 60);

        btnfind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconfind.png"))); // NOI18N
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        getContentPane().add(btnfind);
        btnfind.setBounds(340, 190, 60, 60);

        btnfindanow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfindanow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/iconfindnow.png"))); // NOI18N
        btnfindanow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindanowActionPerformed(evt);
            }
        });
        getContentPane().add(btnfindanow);
        btnfindanow.setBounds(220, 560, 60, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Report1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 886, 631);

        setBounds(0, 0, 902, 669);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        login = new FormLogin();

        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Logout ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(null, "Logout");
                login.setVisible(true);
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(null, "Gagal Logout");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        control.print1();
        
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        home = new FormHome();
        home.getLbnamakasir().setText(namakasir);
        home.getLbidkasir().setText(id_kasir);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu1ActionPerformed
        // TODO add your handling code here:
        menu = new FormMenu();
        menu.getLbnamakasir().setText(namakasir);
        menu.setId_kasir(id_kasir);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnmenu1ActionPerformed

    private void c_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_tglActionPerformed

    private void btnfindallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindallActionPerformed
        // TODO add your handling code here:
        control.tampil_Reportall();
    }//GEN-LAST:event_btnfindallActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
         control.tampil_ReportHari();
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnfindanowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindanowActionPerformed
        // TODO add your handling code here:
        control.tampil_Reportnow();
    }//GEN-LAST:event_btnfindanowActionPerformed

    private void txttotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReport1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReport1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnfindall;
    private javax.swing.JButton btnfindanow;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu1;
    private javax.swing.JButton btnprint;
    private javax.swing.JComboBox<String> c_bln;
    private javax.swing.JComboBox<String> c_tgl;
    private javax.swing.JComboBox<String> c_thn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblreport;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables
}
