/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BJK.form;
import BJK.form.FormLogin;
import BJK.form.FormMenu;
import javax.swing.JLabel;
import BJK.form.FormNewKasir;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Salman Alfarissy
 */
public class FormHome extends javax.swing.JFrame {
    private FormMenu menu;
    private FormLogin login;
    private FormReportMingguan mingguan;
    private FormReportBulanan bulanan;
    private FormReportTahunan tahunan;
    private FormNewKasir newkasir;
    

    /**
     * Creates new form FormHome
     */
    public FormHome() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("src/gambar/logo32.png");
        setIconImage(icon.getImage());
         this.setLocationRelativeTo(null);
    }

    public JLabel getLbidkasir() {
        return lbidkasir;
    }

    public void setLbidkasir(JLabel lbidkasir) {
        this.lbidkasir = lbidkasir;
    }

    public JLabel getLbnamakasir() {
        return lbnamakasir;
    }

    public void setLbnamakasir(JLabel lbnamakasir) {
        this.lbnamakasir = lbnamakasir;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnabout = new javax.swing.JButton();
        btnharian = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        btntahunan = new javax.swing.JButton();
        btnbulanan = new javax.swing.JButton();
        lbidkasir = new javax.swing.JLabel();
        lbnamakasir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnabout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/about.png"))); // NOI18N
        btnabout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnaboutMousePressed(evt);
            }
        });
        btnabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutActionPerformed(evt);
            }
        });
        btnabout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnaboutKeyPressed(evt);
            }
        });
        getContentPane().add(btnabout);
        btnabout.setBounds(820, 570, 40, 40);

        btnharian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ReportMingguan.png"))); // NOI18N
        btnharian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnharianActionPerformed(evt);
            }
        });
        getContentPane().add(btnharian);
        btnharian.setBounds(40, 270, 140, 80);

        btnnew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconAccoun.png"))); // NOI18N
        btnnew.setBorder(null);
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnnew);
        btnnew.setBounds(540, 10, 153, 49);

        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconLogout.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout);
        btnlogout.setBounds(710, 10, 150, 50);

        btnmenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconMenu.png"))); // NOI18N
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu);
        btnmenu.setBounds(40, 180, 140, 80);

        btntahunan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btntahunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ReportTahunan.png"))); // NOI18N
        btntahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntahunanActionPerformed(evt);
            }
        });
        getContentPane().add(btntahunan);
        btntahunan.setBounds(40, 460, 140, 70);

        btnbulanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbulanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ReportBulanan.png"))); // NOI18N
        btnbulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbulananActionPerformed(evt);
            }
        });
        getContentPane().add(btnbulanan);
        btnbulanan.setBounds(40, 360, 140, 80);

        lbidkasir.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        lbidkasir.setForeground(new java.awt.Color(0, 255, 255));
        lbidkasir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbidkasir.setText("Id Kasir");
        getContentPane().add(lbidkasir);
        lbidkasir.setBounds(20, 50, 310, 30);

        lbnamakasir.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        lbnamakasir.setForeground(new java.awt.Color(0, 255, 255));
        lbnamakasir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbnamakasir.setText("nama Kasir");
        getContentPane().add(lbnamakasir);
        lbnamakasir.setBounds(20, 10, 310, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Home.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 886, 631);

        setBounds(0, 0, 902, 669);
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        newkasir = new FormNewKasir();
        newkasir.setIdkasir(lbidkasir.getText());
        newkasir.setNamakasir(lbnamakasir.getText());
        newkasir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        login = new FormLogin();

        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Logout ?");
        switch(opsi){
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(null, "Logout");
                login.setVisible(true);
                dispose();
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(null, "Gagal Logout");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        menu = new FormMenu();
        menu.getLbnamakasir().setText(lbnamakasir.getText());
        menu.setId_kasir(lbidkasir.getText());
        menu.setVisible(true);
        dispose();         
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnbulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbulananActionPerformed
        // TODO add your handling code here:
        bulanan = new FormReportBulanan();
        bulanan.setId_kasir(lbidkasir.getText());
        bulanan.setNamakasir(lbnamakasir.getText());
        bulanan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbulananActionPerformed

    private void btntahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntahunanActionPerformed
        // TODO add your handling code here:
        tahunan = new FormReportTahunan();
        tahunan.setId_kasir(lbidkasir.getText());
        tahunan.setNamakasir(lbnamakasir.getText());
        tahunan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntahunanActionPerformed

    private void btnharianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnharianActionPerformed
        // TODO add your handling code here:
        mingguan = new FormReportMingguan();
        mingguan.setId_kasir(lbidkasir.getText());
        mingguan.setNamakasir(lbnamakasir.getText());
        mingguan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnharianActionPerformed

    private void btnaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutActionPerformed
        // TODO add your handling code here:
        String ket = "BalanjoKuy V 1.0.0 \nCreate by kelompok 4 ";
        JOptionPane.showMessageDialog(null, ket,
                "LogoBalanjokuy",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/gambar/logo32.png"));
    }//GEN-LAST:event_btnaboutActionPerformed

    private void btnaboutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnaboutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaboutKeyPressed

    private void btnaboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaboutMousePressed
        // TODO add your handling code here:
        btnabout.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_btnaboutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btnbulanan;
    private javax.swing.JButton btnharian;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btntahunan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbidkasir;
    private javax.swing.JLabel lbnamakasir;
    // End of variables declaration//GEN-END:variables
}
