/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BJK.form;

import javax.swing.JPasswordField;
import javax.swing.JTextField;
import BJK.controler.ControllerLogin;
import BJK.controler.ControllerMenu;
import BJK.form.FormHome;
import BJK.model.Kasir;
import BJK.model.koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Salman Alfarissy
 */
public class FormLogin extends javax.swing.JFrame {
    
    private Kasir kasir;
    private ControllerLogin controllogin;
    private FormHome home;
    private Statement stat;
    private ResultSet rs;
    private koneksi koneksi;
    Connection conn = koneksi.getKoneksi();

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("src/gambar/logo32.png");
        setIconImage(icon.getImage());
        controllogin = new ControllerLogin(this);
        this.setLocationRelativeTo(null);
    }

    public JTextField getTxtidkasir() {
        return txtidkasir;
    }

    public JPasswordField getTxtpasswd() {
        return txtpasswd;
    }

    public JButton getBtnlogin() {
        return btnlogin;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtidkasir = new javax.swing.JTextField();
        txtpasswd = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtidkasir.setBackground(new java.awt.Color(240, 240, 240));
        txtidkasir.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtidkasir.setBorder(null);
        txtidkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtidkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidkasirActionPerformed(evt);
            }
        });
        txtidkasir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidkasirKeyPressed(evt);
            }
        });
        getContentPane().add(txtidkasir);
        txtidkasir.setBounds(170, 240, 560, 70);

        txtpasswd.setBackground(new java.awt.Color(240, 240, 240));
        txtpasswd.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtpasswd.setBorder(null);
        txtpasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswdActionPerformed(evt);
            }
        });
        txtpasswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswdKeyPressed(evt);
            }
        });
        getContentPane().add(txtpasswd);
        txtpasswd.setBounds(170, 350, 560, 70);

        btnlogin.setBackground(new java.awt.Color(153, 153, 153));
        btnlogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(153, 153, 153));
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconLogin1.png"))); // NOI18N
        btnlogin.setBorder(null);
        btnlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconLogin1.png"))); // NOI18N
        btnlogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/IconLogin1.png"))); // NOI18N
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnloginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnloginMouseReleased(evt);
            }
        });
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        btnlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnloginKeyPressed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(260, 450, 340, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Login.png"))); // NOI18N
        jLabel3.setRequestFocusEnabled(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 886, 631);

        setBounds(0, 0, 902, 669);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswdActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
       try {
            
            kasir = new Kasir();
            home = new FormHome();
           
            
            String idkasir = txtidkasir.getText();
            String passwd = txtpasswd.getText();
            String sql = "SELECT * from tkasir where idkasir='"+idkasir+
                    "' and password= '"+passwd+"'";
            
            stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            int row = 0;
            while (rs.next()){
                row=rs.getRow();
                
                kasir.setIdkasir(rs.getString(1));
                kasir.setNamakasir(rs.getString(2));
                kasir.setPassword(rs.getString(3));
            }
            
            if (row == 1) {
                String nama = kasir.getNamakasir();
                JOptionPane.showMessageDialog(this, nama+" Log In :)");
                home.getLbidkasir().setText(idkasir);
                home.getLbnamakasir().setText(nama);
                home.setVisible(true);
                dispose();
            }
            else{
               JOptionPane.showMessageDialog(null, "Login Gagal Please try again!! :( "); 
            }
        } catch (Exception e) {
            
        }  
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtidkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidkasirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtidkasirActionPerformed

    private void txtidkasirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidkasirKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            controllogin.onKeyPresstxtidkasir(); 
        }
    }//GEN-LAST:event_txtidkasirKeyPressed

    private void txtpasswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            controllogin.onKeyPresstxtpasswd(); 
        }
    }//GEN-LAST:event_txtpasswdKeyPressed

    private void btnloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnloginKeyPressed
        // TODO add your handling code here:
        this.getRootPane().setDefaultButton(btnlogin);
    }//GEN-LAST:event_btnloginKeyPressed

    private void btnloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMousePressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnloginMousePressed

    private void btnloginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnloginMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtidkasir;
    private javax.swing.JPasswordField txtpasswd;
    // End of variables declaration//GEN-END:variables
}
